CODE SEGMENT
ASSUME CS:CODE
ORG 100H
START:
    
    
    MOV AL , 82H    ;FOR THE CONFIG REGISTER
    MOV DX , 0FF2BH ;THE ADDRESS OF THE CONFIG REGISTER OF THE 8255A
    OUT DX , AL     ;TRANSFER 82H TO THE 8255A OUTPUT CONFIG REGISTER
          
          
    ;LABEL WE NEED TO DO FOR THE LOOP
    AGAIN:
    
    MOV DX , 0FF29H  ; THE ADDRESS OF PORT B OF THE 8255 IN THE KIT
    IN AL , DX       ; READ THE DATA AT THE ADDRESS IN THE DX (FF29H)
                     ; AND STORE IT IN AL
    
    
    
    MOV DX , 0FF28H ; THE ADDRESS OF THE PORT A WHICH INTERFACING THE LEDS
    OUT DX , AL     ; TRANSFER THE DATA WE HAVE FROM AL 
                    ; WHICH IS FROM THE SWITCHES TO ADDRESS 0FF28H
                    ; WHICH IS PORT A CONNECTED TO THE LEDS
    JMP AGAIN       ; GET BACK AND READ THE SWITCHES AND REPEAT THE PROCESS
    
         
         
         
END START
CODE ENDS
